lang_zh_cn = {
    'Home': '主页',
    'Subscription': '申购',
    'Redemption': '赎回',
    'Dividend': '分红',
    'Code': '代码',
    'Name': '名称',
    'Date': '日期',
    'Baseline': '比较基准',
    'StocksPct': '权益类比例',
    'BondsPct': '固收比例',
    'Rating': '评级',
    'Capital': '本金',
    'Share': '份额',
    'Price': '净值',
    'Due': '到期日',
    'Ok': '确定',
    'Cancel': '取消',
    'Add': '新增',
    'Exit': '退出',
    'Refresh': '刷新',
    'Product': '产品',
    'Last Update': '上次净值更新',
    'Last Price': '上次净值',
    'Update Price': '更新净值',
    'Add Subscription': '添加申购',
    'Add Redemption': '添加赎回',
    'Add Dividend': '添加分红',
    'Existed': '已存在',
    'Skip Update': '跳过更新',
    'Information': '信息',
    'Actions': '操作',
    'History': '历史',
    'Duplicate': '重复',
    'Data Wrong': '数据错误',
    'Withdrawn': '赎回金额',
    'Report': '报告',
    'IRR': '内部收益率',
    'Profit': '盈利',
    'Value': '价值',
}

lang_dict = {
    'zh_cn': lang_zh_cn
}

lang = lang_dict['zh_cn']
